version: '3.7'

services:
  web:
    build: ./project
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
